### PR TITLE
Up french translation and tp2

### PR DESCRIPTION
**Pull request by 11jo**
Hello Morpheus,

I just [discovered this](https://github.com/11jo/Skills-and-Abilities/commit/e15b593335c58e6f57c11c4eb8be5900422e117d#diff-9470dd9e5b6e0b08c41834328092643b0afda044a4b36a5cb04a0971841faaa8), if it's good for you I'll do the same for Forgotten Armament !

This will allow players to enjoy your latest version without "Undefined strings".

### CODE REVIEW

**Comment by 11jo** [comment]
Sorry, the entries are aligned in my file and I don't understand the offset for ~skills-and-abilities/languages/english/setup.tra~ and ~skills-and-abilities/languages/french/fighter.tra~

If you prefer that I cancel the pull request and redo it, no problem!

**Comment by morpheus562** [comment]
Thank you for all the work! Did you update them to align now, or is there more stuff that needs to be done before I accept?

**Comment by 11jo** [comment]
Thanks, 

they should be aligned now, so it's good for me !

And it's pretty cool that yours mods become so extensive !!!

**Comment by morpheus562** [comment]
Thank you, I am happy you are enjoying it!

**Pull request merged**
